// <auto-generated />
namespace PetStore.Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mgtPetEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mgtPetEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "202308131812510_mgt-Pet-Entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
